using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace _9_Problem_9_3_Properties
{
    class Person
    {
        // Encapsulating class variables (Hiding and protecting the variables)
        // Class fields are hidden because they have private access modifier
        // We can access these fields using get/set methods or properties
        private string newName;
        private double newHeight;
        private double newWeight;

        // type ctor word, then press tab button twice to generate contructor
        // Default constructor is used to se class variables to default values
        // Default value for string is null
        // Default value for int is 0, double is 0.0
        public Person()
        {

        }

        // Overloaded constructor with 3 parameters
        public Person(string Name, double Height, double Weight)
        {
            newName = Name;
            newHeight = Height;
            newWeight = Weight;
        }

        // Creating Accessors and Mutators (Getters and Setters methods) using properties
        // Properties do not have (), in ohter words they are NOT methods
        public string personName
        {
            // Get reads the class field value
            get { return newName; }

            // set will always be equal to value
            // Value is a virtual variable generated by the compiler
            // whatever the value the class field is set to, it will always be a value
            set { newName = value; }
        }

        public double personHeight
        {
            get { return newHeight; }
            set { newHeight = value;  }
        }

        public double personWeight
        {
            get { return newWeight;  }
            set { newWeight = value;  }
        }
    }
}
